### PR TITLE
[MDEPLOY-206] Deploy improvements

### PR DESCRIPTION
**Pull request by cstamas**
Changes:
* remove deployInParallel, deploy plugin when deployAtEnd always creates one deploy request and passes it to resolver
* remove misleading log "deferring deploy" when the module is actually last and is not deferred by deploys all

### CODE REVIEW

**Review by slawekjaranowski — APPROVED** [review]

**Comment by slawekjaranowski** [comment]
we should link with https://issues.apache.org/jira/browse/MDEPLOY-206 and reopen it until change in resolver will be done

**Comment by slawekjaranowski** [comment]
Please also remove  IT `deploy-at-end-parallel` it use removed parameter

**Comment by cstamas** [comment]
Done

**Review by slawekjaranowski — APPROVED** [review]

**Comment by jira-importer** [comment]
Resolve #480

**Comment by jira-importer** [comment]
Resolve #480

**Pull request merged**
