### PR TITLE
MDEPLOY-245: Remove the remnants of the obsolete `updateReleaseInfo` parameter.

### PR DESCRIPTION
**Pull request by vovkss**
Jira: MDEPLOY-240 - trivial follow-up fix.

 - [X] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

### CODE REVIEW

**Comment by khmarbaise** [comment]
Can you please create a new JIRA with a reference to the old one and describe that information has not been removed completely.

**Comment by vovkss** [comment]
Sure, https://issues.apache.org/jira/browse/MDEPLOY-245

**Comment by khmarbaise** [comment]
Thanks for your contribution.

**Comment by jira-importer** [comment]
Resolve #383

**Pull request closed without merging**
