### PR TITLE
[MDEPLOY-292] Require Java 8

### PR DESCRIPTION
**Pull request by slachiewicz**

### CODE REVIEW

**Comment by cstamas** [comment]
I'd postpone this for 3.1.0. We want 3.0.0 be usable with maven 3.8.x as well, and current master will work just fine.

**Comment by slachiewicz** [comment]
Sure. Could you create jira tag for 3.1.0?

**Comment by slawekjaranowski** [comment]
@slachiewicz , @cstamas - rebased .. I hope can be merged now

**Comment by jira-importer** [comment]
Resolve #401

**Pull request merged**
