### PR TITLE
Revert "[MDEPLOY-231] - Move checksum generation from install to depl…

### PR DESCRIPTION
**Pull request by michael-o**
…oy plugin"

This reverts commit 83b2d51cb3427a54ea465ff836c68da18accd426.

Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MPH) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[MPH-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MPH-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [ ] You have run the integration tests successfully (`mvn -Prun-its clean verify`).

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [ ] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by rfscholte** [comment]
I think the description is wrong, because MDEPLOY-231 is still valid to me. It looks like you're only restoring an IT, which is not the same.

**Comment by michael-o** [comment]
I am confused by your statement. I do not restore the IT, I am removing it. Please explain how you understand the issue is still valid.

**Comment by michael-o** [comment]
Your understanding is that the commit title should read: "Revert IT of MDEPLOY-231"?

**Comment by rfscholte** [comment]
I was a bit confused, but it is not a complete revert, just partial.
However, I think it is valid to keep this IT. It in an _integration test_ that ensures the checksums are generated. If Artifact Resolver is being refactored or this plugin switches to a different implementation, it is good to verify the checksums will still be there.

**Comment by michael-o** [comment]
The problem with this is that it is not portable. It does not know which checksums are generated. It is assumed, but nothing else.

**Comment by michael-o** [comment]
See my comment: https://issues.apache.org/jira/browse/MDEPLOY-231?focusedCommentId=17253097&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17253097

**Comment by rfscholte** [comment]
But based on the Maven version we know the default generated checksum right?

**Comment by michael-o** [comment]
> 
> 
> But based on the Maven version we know the default generated checksum right?

Theoretically, yes. You could add this to the configuration somehow.

**Comment by slawekjaranowski** [comment]
I would to refresh this PR ...

Simply m-deploy-p is not responsible for checksum generation, so should not be tested here ...

**Comment by michael-o** [comment]
> I would to refresh this PR ...
> 
> Simply m-deploy-p is not responsible for checksum generation, so should not be tested here ...

This is also my stance.  Please go on.

**Comment by slawekjaranowski** [comment]
Will be done in another PR 😄

**Comment by michael-o** [comment]
Please delete this branch when this is done.

**Comment by jira-importer** [comment]
Resolve #494

**Pull request closed without merging**
